import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppNavbar from "@/components/app.navbar";
import Sidebar from "@/components/app.sidebar";
import AuthProvider from "@/app/context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <AppNavbar />
          <div className="flex flex-row">
            <div className="h-screen">
              <Sidebar />
            </div>
            <div>{children}</div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
